source = ~/.config/hypr/themes/catppuccin-mocha.conf

# colors - catppuccin theme
background = $base
base = $surface0
alternate_base = $surface0
text = $text
bright_text = $text
accent = $rosewater
accent_secondary = $mauve

# fonts
font_family = monospace

# borders
rounding_large = 8
rounding_small = 4
